version: '3'
services:
  # nest-app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - 8080:8080
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - mysql-db
  mysql-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: qwer1595
      MYSQL_DATABASE: nest-test
      MYSQL_USER: admin
      MYSQL_PASSWORD: qwer1595
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    environment:
      - TZ=Asia/Seoul

volumes:
  mysql-data:
